const router=require('express').Router();const {db}=require('../db');const {requireAuth}=require('../auth');const engine=require('../trading-engine');const {asyncHandler}=require('../middleware/error');router.use(requireAuth,(req,res,next)=>req.user.role==='owner'?next():res.status(403).json({error:{code:'OWNER_ONLY',message:'Owner access required'}}));
function audit(req,action,target,detail){db.prepare('INSERT INTO admin_audit(actor_id,target_user_id,action,detail) VALUES(?,?,?,?)').run(req.user.sub,target,action,JSON.stringify(detail||{}))}
router.get('/overview',asyncHandler((req,res)=>{const users=db.prepare('SELECT COUNT(*) n FROM users').get().n,pending=db.prepare("SELECT COUNT(*) n FROM users WHERE approval_status='pending'").get().n,bots=db.prepare("SELECT COUNT(*) n FROM bot_sessions WHERE status='running'").get().n,trades=db.prepare("SELECT COUNT(*) n FROM positions WHERE status='closed'").get().n,aum=db.prepare('SELECT COALESCE(SUM(equity),0) n FROM equity_snapshots WHERE id IN (SELECT MAX(id) FROM equity_snapshots GROUP BY user_id)').get().n;res.json({users,pending,bots,trades,aum})}));
router.get('/users',asyncHandler((req,res)=>{const q=String(req.query.q||'').trim(),status=String(req.query.status||'').trim();let sql=`SELECT u.id,u.email,u.full_name,u.role,u.approval_status,u.bot_access,u.rejection_reason,u.created_at,b.status bot_status,COALESCE(es.equity,0) equity,COALESCE(op.open_count,0) open_count FROM users u LEFT JOIN bot_sessions b ON b.user_id=u.id LEFT JOIN (SELECT user_id,MAX(id) mid FROM equity_snapshots GROUP BY user_id) mx ON mx.user_id=u.id LEFT JOIN equity_snapshots es ON es.id=mx.mid LEFT JOIN (SELECT user_id,COUNT(*) open_count FROM positions WHERE status='open' GROUP BY user_id) op ON op.user_id=u.id WHERE u.role!='owner'`;const args=[];if(q){sql+=' AND (u.email LIKE ? OR u.full_name LIKE ?)';args.push(`%${q}%`,`%${q}%`)}if(status){sql+=' AND u.approval_status=?';args.push(status)}sql+=' ORDER BY u.created_at DESC';res.json(db.prepare(sql).all(...args))}));
router.post('/users/:id/approve',asyncHandler((req,res)=>{const id=Number(req.params.id);db.prepare("UPDATE users SET approval_status='approved',bot_access=?,rejection_reason=NULL,approved_at=datetime('now') WHERE id=?").run(req.body?.grantBotAccess===false?'blocked':'active',id);audit(req,'user.approve',id,{grantBotAccess:req.body?.grantBotAccess!==false});res.json({ok:true})}));
router.post('/users/:id/reject',asyncHandler((req,res)=>{const id=Number(req.params.id),reason=String(req.body?.reason||'Rejected by owner').trim();db.prepare("UPDATE users SET approval_status='rejected',bot_access='blocked',rejection_reason=? WHERE id=?").run(reason,id);engine.stopForUser(id,'access rejected');audit(req,'user.reject',id,{reason});res.json({ok:true})}));
router.post('/users/:id/bot-access',asyncHandler((req,res)=>{const id=Number(req.params.id),access=req.body?.access==='active'?'active':'blocked';db.prepare('UPDATE users SET bot_access=? WHERE id=?').run(access,id);if(access!=='active')engine.stopForUser(id,'bot access blocked by owner');audit(req,'user.bot_access',id,{access});res.json({ok:true})}));
router.post('/users/:id/stop-bot',asyncHandler((req,res)=>{const id=Number(req.params.id);engine.stopForUser(id,'stopped by owner');audit(req,'bot.stop',id,{});res.json({ok:true})}));
router.get('/trades',asyncHandler((req,res)=>res.json(db.prepare('SELECT p.*,u.email FROM positions p JOIN users u ON u.id=p.user_id ORDER BY COALESCE(p.closed_at,p.opened_at) DESC LIMIT ?').all(Math.min(Number(req.query.limit)||200,1000)))));
router.get('/audit',asyncHandler((req,res)=>res.json(db.prepare('SELECT a.*,u.email actor_email FROM admin_audit a LEFT JOIN users u ON u.id=a.actor_id ORDER BY a.created_at DESC LIMIT ?').all(Math.min(Number(req.query.limit)||200,1000)))));
module.exports=router;
