const router=require('express').Router();const {db}=require('../db');const {requireAuth}=require('../auth');const engine=require('../trading-engine');const broker=require('../brokers');const {enc}=require('../crypto');const config=require('../config');const {asyncHandler}=require('../middleware/error');
router.use(requireAuth);
function approved(req){const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.sub);return u.role==='owner'||(u.approval_status==='approved'&&u.bot_access==='active')}
router.get('/dashboard',asyncHandler(async(req,res)=>{const userId=req.user.sub;const u=db.prepare('SELECT * FROM users WHERE id=?').get(userId),snap=db.prepare('SELECT * FROM equity_snapshots WHERE user_id=? ORDER BY id DESC LIMIT 1').get(userId),positions=db.prepare("SELECT * FROM positions WHERE user_id=? AND status='open' ORDER BY opened_at DESC").all(userId),pnl=db.prepare('SELECT COALESCE(SUM(net_pnl),0) net,COUNT(*) total,SUM(CASE WHEN net_pnl>0 THEN 1 ELSE 0 END) wins FROM positions WHERE user_id=? AND status=\'closed\'').get(userId),curve=db.prepare('SELECT date(taken_at) day,MAX(equity) equity FROM equity_snapshots WHERE user_id=? GROUP BY date(taken_at) ORDER BY day DESC LIMIT 90').all(userId).reverse(),bot=db.prepare('SELECT * FROM bot_sessions WHERE user_id=?').get(userId);let live=null;try{live=await engine.syncAccount(userId)}catch{};res.json({user:{id:u.id,email:u.email,full_name:u.full_name,role:u.role,approval_status:u.approval_status,bot_access:u.bot_access},account:live?.account||{equity:snap?.equity,cash:snap?.cash},positions:live?.positions||positions,equityCurve:curve,performance:{netPnl:pnl.net,totalTrades:pnl.total,winRate:pnl.total?pnl.wins/pnl.total*100:0},bot})}));
router.get('/compliance',asyncHandler((req,res)=>res.json({profile:config.shariah.profile,screening:config.shariah,watchlist:config.trading.watchlist.map(s=>require('../shariah/screening').screenSymbol(s))})));
router.get('/settings',asyncHandler(async(req,res)=>{const r=db.prepare('SELECT * FROM risk_settings WHERE user_id=?').get(req.user.sub);const b=db.prepare('SELECT id,provider,server,login,tickerall_account_id,status,last_sync_at FROM broker_accounts WHERE user_id=? ORDER BY id DESC LIMIT 1').get(req.user.sub);res.json({risk:r,broker:b})}));
router.put('/settings/risk',asyncHandler((req,res)=>{if(!approved(req))return res.status(403).json({error:{code:'ACCESS_GATE',message:'Owner approval and active bot access are required'}});const id=req.user.sub,x=req.body||{};db.prepare(`UPDATE risk_settings SET risk_percent=?,daily_loss_cap=?,max_position_percent=?,max_concurrent_positions=?,cash_reserve_percent=?,min_reward_risk=?,min_confidence=? WHERE user_id=?`).run(Number(x.riskPercent),Number(x.dailyLossCap),Number(x.maxPositionPercent),Number(x.maxConcurrentPositions),Number(x.cashReservePercent),Number(x.minRewardRisk),Number(x.minConfidence),id);res.json({ok:true})}));
router.post('/broker/connect',asyncHandler(async(req,res)=>{if(!approved(req))return res.status(403).json({error:{code:'ACCESS_GATE',message:'Owner approval and active bot access are required'}});const {server,login,password,brokerType='mt5',terminalType='MOBILE'}=req.body||{};if(!server||!login||!password)return res.status(400).json({error:{code:'BAD_INPUT',message:'Server, login and password are required'}});const session=await broker.connect({broker:brokerType,server,account:login,password,terminalType});const existing=db.prepare('SELECT id FROM broker_accounts WHERE user_id=? AND login=?').get(req.user.sub,String(login));if(existing)db.prepare('UPDATE broker_accounts SET server=?,encrypted_password=?,tickerall_account_id=?,terminal_type=?,status=? WHERE id=?').run(server,enc(password),session.accountId,terminalType,session.status,existing.id);else db.prepare('INSERT INTO broker_accounts(user_id,server,login,encrypted_password,tickerall_account_id,terminal_type,status) VALUES(?,?,?,?,?,?,?)').run(req.user.sub,server,String(login),enc(password),session.accountId,terminalType,session.status);res.json({ok:true,accountId:session.accountId,status:session.status})}));
router.post('/broker/disconnect',asyncHandler(async(req,res)=>{const b=db.prepare('SELECT * FROM broker_accounts WHERE user_id=? ORDER BY id DESC LIMIT 1').get(req.user.sub);if(b?.tickerall_account_id){try{await broker.disconnect(b.tickerall_account_id)}catch{}}if(b)db.prepare("UPDATE broker_accounts SET status='disconnected' WHERE id=?").run(b.id);engine.stopForUser(req.user.sub,'broker disconnected');res.json({ok:true})}));
router.post('/bot/start',asyncHandler((req,res)=>{if(!approved(req))return res.status(403).json({error:{code:'ACCESS_GATE',message:'Owner approval and active bot access are required'}});if(config.trading.liveOrderExecution)return res.status(501).json({error:{code:'LIVE_EXECUTION_NOT_INCLUDED','message':'Live order execution is not included in this safety-reviewed build.'}});engine.startForUser(req.user.sub);res.json({ok:true,mode:'monitoring-and-signals'})}));
router.post('/bot/stop',asyncHandler((req,res)=>{engine.stopForUser(req.user.sub,'stopped by user');res.json({ok:true})}));
router.post('/bot/tick',asyncHandler(async(req,res)=>{if(!approved(req))return res.status(403).json({error:{code:'ACCESS_GATE',message:'Owner approval and active bot access are required'}});res.json(await engine.tick(req.user.sub))}));
router.post('/backtest',asyncHandler(async(req,res)=>{const b=db.prepare('SELECT * FROM broker_accounts WHERE user_id=? ORDER BY id DESC LIMIT 1').get(req.user.sub);if(!b?.tickerall_account_id)return res.status(400).json({error:{code:'NO_BROKER','message':'Connect a broker account first'}});const {symbol='AAPL',timeframe='H1',limit=500}=req.body||{};const screening=require('../shariah/screening').screenSymbol(String(symbol).toUpperCase());if(screening.status!=='compliant')return res.status(400).json({error:{code:'SCREEN_FAIL','message':screening.notes||'Symbol is not compliant'}});const candles=await broker.candles(b.tickerall_account_id,String(symbol).toUpperCase(),timeframe,Math.min(Number(limit)||500,5000));const result=require('../backtest').simulate(candles,{equity:10000,...config.risk,maxConcurrentPositions:config.trading.maxConcurrentPositions});res.json({symbol,timeframe,candles:candles.length,result})}));
router.get('/signals',asyncHandler((req,res)=>res.json(db.prepare('SELECT * FROM signals WHERE user_id=? ORDER BY id DESC LIMIT 200').all(req.user.sub))));
module.exports=router;
