const config=require('./config');const {db}=require('./db');const broker=require('./brokers');const ai=require('./ai/signal-engine');const risk=require('./risk');const screening=require('./shariah/screening');
const active=new Map();const ticking=new Set();
function now(){return new Date().toISOString()}
function settings(userId){return db.prepare('SELECT * FROM risk_settings WHERE user_id=?').get(userId)||{risk_percent:config.risk.riskPercent,daily_loss_cap:config.risk.dailyLossCap,max_position_percent:config.risk.maxPositionPercent,max_concurrent_positions:config.trading.maxConcurrentPositions,cash_reserve_percent:config.risk.cashReservePercent,min_reward_risk:config.risk.minRewardRisk,min_confidence:config.risk.minConfidence}}
async function syncAccount(userId){const ba=db.prepare('SELECT * FROM broker_accounts WHERE user_id=? ORDER BY id DESC LIMIT 1').get(userId);if(!ba?.tickerall_account_id)return null;const a=await broker.account(ba.tickerall_account_id);db.prepare('INSERT INTO equity_snapshots(user_id,equity,cash) VALUES(?,?,?)').run(userId,a.account?.equity??a.account?.balance,a.account?.balance);db.prepare('UPDATE broker_accounts SET status=?,last_sync_at=? WHERE id=?').run(a.status||'online',now(),ba.id);return {account:a.account||{},positions:a.positions||[],accountId:ba.tickerall_account_id}}
async function tick(userId){if(ticking.has(userId))return {skipped:true};ticking.add(userId);try{const session=db.prepare('SELECT * FROM bot_sessions WHERE user_id=?').get(userId);if(!session||session.status!=='running')return {skipped:true};const s=settings(userId);const live=await syncAccount(userId);if(!live)throw new Error('No connected broker account');const equity=Number(live.account.equity??live.account.balance??0);const date=new Date().toISOString().slice(0,10);if(session.day_anchor_date!==date){db.prepare('UPDATE bot_sessions SET day_anchor_equity=?,day_anchor_date=? WHERE user_id=?').run(equity,date,userId)}const anchor=Number(session.day_anchor_equity||equity);if(anchor>0&&((anchor-equity)/anchor)*100>=Number(s.daily_loss_cap)){db.prepare('UPDATE bot_sessions SET status=\'halted\',halt_reason=? WHERE user_id=?').run('Daily loss cap reached',userId);return {halted:true}}
for(const symbol of config.trading.watchlist){const sc=screening.screenSymbol(symbol);if(sc.status!=='compliant')continue;const c=await broker.candles(live.accountId,symbol,'H1',200);const sig=ai.evaluate(c);if(!sig||sig.confidence<Number(s.min_confidence))continue;const levels=risk.protectiveLevels({entry:sig.entry,stop:sig.stop,target:sig.target,minRewardRisk:Number(s.min_reward_risk)});if(!levels.ok)continue;const openCount=db.prepare("SELECT COUNT(*) n FROM positions WHERE user_id=? AND status='open'").get(userId).n;if(Number(s.max_concurrent_positions)>0&&openCount>=Number(s.max_concurrent_positions))continue;const sizing=risk.sizePosition({equity,cash:Number(live.account.balance??equity),entry:levels.entry,stop:levels.stop,settings:{riskPercent:Number(s.risk_percent),maxPositionPercent:Number(s.max_position_percent),cashReservePercent:Number(s.cash_reserve_percent)}});if(sizing.qty<=0)continue;db.prepare('INSERT INTO signals(user_id,symbol,strategy,confidence,entry,stop,target,outcome) VALUES(?,?,?,?,?,?,?,?)').run(userId,symbol,sig.strategy,sig.confidence,levels.entry,levels.stop,levels.target,'candidate');}
db.prepare('UPDATE bot_sessions SET tick_count=tick_count+1,last_tick_at=? WHERE user_id=?').run(now(),userId);return {ok:true,account:live.account,positions:live.positions}}
finally{ticking.delete(userId)}}
function startForUser(userId){if(active.has(userId))return;db.prepare("UPDATE bot_sessions SET status='running',halt_reason=NULL WHERE user_id=?").run(userId);const timer=setInterval(()=>tick(userId).catch(e=>db.prepare('UPDATE bot_sessions SET status=\'halted\',halt_reason=? WHERE user_id=?').run(e.message,userId)),config.trading.tickMs);active.set(userId,timer);return true}
function stopForUser(userId,reason='stopped'){const t=active.get(userId);if(t)clearInterval(t);active.delete(userId);db.prepare('UPDATE bot_sessions SET status=?,halt_reason=? WHERE user_id=?').run('stopped',reason,userId)}
function resumeAll(){const rows=db.prepare("SELECT user_id FROM bot_sessions WHERE status='running'").all();for(const r of rows)startForUser(r.user_id);return rows.length}
function shutdownAll(){for(const id of active.keys())stopForUser(id,'shutdown')}
module.exports={startForUser,stopForUser,shutdownAll,resumeAll,tick,syncAccount};
